spring:
  datasource:
    url: jdbc:mysql://bnk-data:3306/bnk
    username: trucker
    password: trucker
    driver-class-name: com.mysql.cj.jdbc.Driver

bnk:
  api:
    vendor:
      uri: http://bnk-api-vendor:8080/vendors
    category:
      uri: http://bnk-api-category:8080/categories
    customer:
      uri: http://bnk-api-customer:8080/customers
    bank:
      uri: http://bnk-api-bank:8080/banks
    party:
      uri: http://bnk-api-party:8080/parties
    account:
      uri: http://bnk-api-account:8080/accounts
management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always
