spring:
  datasource:
    url: jdbc:mysql://bnk-data:3306/bnk
    username: trucker
    password: '{cipher}0076a723ffeb617130c5674cb5e0d00d9932377726c934b38c4f8131f5438616'
    driver-class-name: com.mysql.cj.jdbc.Driver

bnk:
  api:
    vendor:
      uri: http://bnk-api-vendor:8080/vendors
    category:
      uri: http://bnk-api-category:8080/categories
    customer:
      uri: http://bnk-api-customer:8080/customers
    bank:
      uri: http://bnk-api-bank:8080/banks
    party:
      uri: http://bnk-api-party:8080/parties
    account:
      uri: http://bnk-api-account:8080/accounts
